
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: zaikron/php-laravel:latest
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: blog
          - name: MYSQL_USER
            value: blogger
          - name: MYSQL_PASSWORD
            value: password


